# Generated by Django 4.2.6 on 2023-11-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_admision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='periodo',
            field=models.IntegerField(default=2023),
        ),
    ]
