# Generated by Django 4.2.6 on 2023-11-19 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('contrasenia1', models.CharField(blank=True, max_length=128, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Último Acceso')),
                ('es_activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Administrador',
            },
        ),
    ]
