# Generated by Django 4.2.6 on 2023-11-20 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('m_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(choices=[[0, 'Matematicas'], [1, 'Lenguaje'], [2, 'Ingles'], [3, 'Historia'], [4, 'Ed. Fisica']])),
                ('sigla', models.IntegerField(choices=[[0, 'MAT'], [1, 'LEN'], [2, 'ING'], [3, 'HIST'], [4, 'EFI']])),
            ],
            options={
                'db_table': 'Asignatura',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(choices=[[0, '1° basico'], [1, '2° basico'], [2, '3° basico'], [3, '4° basico'], [4, '5° basico'], [5, '6° basico'], [6, '7° basico'], [7, '8° basico'], [8, '1° medio'], [9, '2° medio'], [10, '3° medio'], [11, '4° medio']])),
                ('seccion', models.IntegerField(choices=[[0, 'A'], [1, 'B']])),
                ('periodo', models.IntegerField(default=2023)),
            ],
            options={
                'db_table': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionPlanificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('ponderacion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_academico.asignatura')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_academico.curso')),
            ],
            options={
                'db_table': 'Evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_user.estudiante')),
                ('evaluacion_planificada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_academico.evaluacionplanificada')),
            ],
            options={
                'db_table': 'Calificacion',
            },
        ),
        migrations.AddField(
            model_name='asignatura',
            name='cursos',
            field=models.ManyToManyField(related_name='cursos', to='m_academico.curso'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='docentes',
            field=models.ManyToManyField(related_name='docentes', to='m_user.docente'),
        ),
    ]
