# Generated by Django 4.2.6 on 2023-11-15 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Apoderado',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[[0, 'Administrador'], [1, 'Docente'], [2, 'Apoderado'], [3, 'Estudiante']], max_length=15)),
            ],
            options={
                'db_table': 'Tipo_usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('num_rut', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('pnombre', models.CharField(max_length=30)),
                ('snombre', models.CharField(blank=True, max_length=30, null=True)),
                ('appat', models.CharField(max_length=30)),
                ('apmat', models.CharField(max_length=30)),
                ('fec_nac', models.DateField()),
                ('nacionalidad', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[[0, 'Femenino'], [1, 'Masculino'], [2, 'No aplica']], max_length=9)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentezco', models.CharField(max_length=10)),
                ('Apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_user.apoderado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_user.tipousuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_user.usuario')),
            ],
            options={
                'db_table': 'Estudiante',
            },
        ),
        migrations.AddField(
            model_name='apoderado',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_user.tipousuario'),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_user.usuario'),
        ),
    ]
