# Generated by Django 4.2.6 on 2023-11-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderado',
            name='contrasenia',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
