# Generated by Django 4.2.6 on 2023-11-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_user', '0002_alter_tipousuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.IntegerField(choices=[[0, 'Femenino'], [1, 'Masculino'], [2, 'No aplica']]),
        ),
    ]
