# Generated by Django 4.2.6 on 2023-11-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_user', '0002_alter_apoderado_contrasenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderado',
            name='contrasenia',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
