# Generated by Django 4.2.6 on 2023-11-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_user', '0003_alter_usuario_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='num_rut',
            new_name='num_run',
        ),
    ]
