# Generated by Django 4.2.6 on 2023-11-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_user', '0004_rename_num_rut_usuario_num_run'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='num_run',
            new_name='num_rut',
        ),
    ]
